//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otobus.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=F:\\Eray\\Dosyalar\\24.03.2017\\O" +
            "tobus\\Veritabani\\Otobus.mdf;Integrated Security=True;Connect Timeout=30")]
        public string OtobusConnectionString {
            get {
                return ((string)(this["OtobusConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TAN;Initial Catalog=\"D:\\DIĞER\\ERAY\\ERAY\\DOSYALAR\\OTOBÜS VERITABANı\\OT" +
            "OBUS.MDF\";Persist Security Info=True;User ID=sa;Password=123456")]
        public string D__DIĞER_ERAY_ERAY_DOSYALAR_OTOBÜS_VERITABANı_OTOBUS_MDFConnectionString {
            get {
                return ((string)(this["D__DIĞER_ERAY_ERAY_DOSYALAR_OTOBÜS_VERITABANı_OTOBUS_MDFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\\App_data\\Otobus.mdb;" +
            "Persist Security Info=True")]
        public string OtobusConnectionString1 {
            get {
                return ((string)(this["OtobusConnectionString1"]));
            }
        }
    }
}
